$(document).ready(function(){
    $(".img").click(function(){
        $(".img").hide();
        $(".what-showing2").show();
    });
    $(".what-showing2").click(function(){
        $(".what-showing2").hide();
        $(".img").show();
    });
      
    $(".DM").click(function(){
        $(".DM").hide();
        $(".what-showing3").show();
    });
    $(".what-showing3").click(function(){
        $(".what-showing3").hide();
        $(".DM").show();
    });

    $(".PM").click(function(){
        $(".PM").hide();
        $(".what-showing4").show();
    });
    $(".what-showing4").click(function(){
        $(".what-showing4").hide();
        $(".PM").show();
    });
});

$(document).ready(function(){
    $("#work4").mouseenter(function(){
        $("#work4").fadeToggle();
        $("#work04").fadeToggle();
    });
    $("#work04").mouseleave(function(){
        $("#work04").fadeToggle();
        $("#work4").fadeToggle();
    });
    $("#work3").mouseenter(function(){
        $("#work3").fadeToggle();
        $("#work03").fadeToggle();
    });
    $("#work03").mouseleave(function(){
        $("#work03").fadeToggle();
        $("#work3").fadeToggle();
    });
    $("#work2").mouseenter(function(){
        $("#work2").fadeToggle();
        $("#work02").fadeToggle();
    });
    $("#work02").mouseleave(function(){
        $("#work02").fadeToggle();
        $("#work2").fadeToggle();
    });
    $("#work1").mouseenter(function(){
        $("#work1").fadeToggle();
        $("#work01").fadeToggle();
    });
    $("#work01").mouseleave(function(){
        $("#work01").fadeToggle();
        $("#work1").fadeToggle();
    });
    
});
